(function(){'use strict';
'use strict';var e,f="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},g="object"===typeof f.global&&f.global?f.global:"object"===typeof global&&global&&global.Object===Object?global:this;f.global=g;f.exportsNamespace="object"===typeof f.exportsNamespace&&f.exportsNamespace?f.exportsNamespace:g;g.Object.freeze(f);var aa={envInfo:f,semantics:{asInstanceOfs:2,arrayIndexOutOfBounds:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.28",globalThis:this};g.Object.freeze(aa);
g.Object.freeze(aa.semantics);var n=g.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},ba=g.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},ca=0,da=g.WeakMap?new g.WeakMap:null;function q(a){return function(b,c){return!(!b||!b.$classData||b.$classData.E!==c||b.$classData.C!==a)}}
function ea(a){for(var b in a)return b}function fa(a,b,c){var d=new a.aa(b[c]);if(c<b.length-1){a=a.G;c+=1;for(var k=d.Ga,h=0;h<k.length;h++)k[h]=fa(a,b,c)}return d}function ha(a){switch(typeof a){case "string":return r(ia);case "number":var b=a|0;return b===a?ja(b)?r(ka):la(b)?r(ma):r(na):"number"===typeof a?r(oa):r(pa);case "boolean":return r(qa);case "undefined":return r(ra);default:return null===a?a.pc():sa(a)?r(ta):a&&a.$classData?r(a.$classData):null}}
function ua(a){switch(typeof a){case "string":return va(wa(),a);case "number":return xa(ya(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.o():null===da?42:za(a)}}
var za=null!==da?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return ua(a);default:if(null===a)return 0;var b=da.get(a);void 0===b&&(ca=b=ca+1|0,da.set(a,b));return b}}:function(a){if(a&&a.$classData){var b=a.$idHashCode$0;if(void 0!==b)return b;if(g.Object.isSealed(a))return 42;ca=b=ca+1|0;return a.$idHashCode$0=b}return null===a?0:ua(a)};function ja(a){return"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0}
function la(a){return"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0}function u(){this.V=this.aa=void 0;this.C=this.G=this.k=null;this.E=0;this.Ja=null;this.S="";this.g=this.Q=this.R=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function v(a,b,c){var d=new u;d.k={};d.G=null;d.Ja=a;d.S=b;d.g=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function w(a,b,c,d,k,h,m){var l=new u,p=ea(a);h=h||function(t){return!!(t&&t.$classData&&t.$classData.k[p])};m=m||function(t,G){return!!(t&&t.$classData&&t.$classData.E===G&&t.$classData.C.k[p])};l.V=k;l.k=c;l.S="L"+b+";";l.g=m;l.name=b;l.isInterface=!1;l.isRawJSType=!!d;l.isInstance=h;return l}
function Aa(a){function b(l){if("number"===typeof l){this.Ga=Array(l);for(var p=0;p<l;p++)this.Ga[p]=k}else this.Ga=l}var c=new u,d=a.Ja,k="longZero"==d?x().P:d;b.prototype=new y;b.prototype.constructor=b;b.prototype.$classData=c;d="["+a.S;var h=a.C||a,m=a.E+1;c.aa=b;c.V=Ba;c.k={a:1,Sa:1,c:1};c.G=a;c.C=h;c.E=m;c.Ja=null;c.S=d;c.R=void 0;c.Q=void 0;c.g=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(l){return h.g(l,m)};return c}
function r(a){if(!a.R){var b=new z;b.p=a;a.R=b}return a.R}function Ca(a){a.Q||(a.Q=Aa(a));return a.Q}u.prototype.getFakeInstance=function(){if(this===ia)return"some string";if(this===qa)return!1;if(this===ka||this===ma||this===na||this===oa||this===pa)return 0;if(this===ta)return x().P;if(this!==ra)return{$classData:this}};u.prototype.getSuperclass=function(){return this.V?r(this.V):null};u.prototype.getComponentType=function(){return this.G?r(this.G):null};
u.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=Ca(b);return fa(b,a,0)};var Da=v(!1,"Z","boolean"),Ea=v(0,"C","char"),Fa=v(0,"B","byte"),Ga=v(0,"S","short"),Ha=v(0,"I","int"),Ia=v("longZero","J","long"),Ja=v(0,"F","float"),Ka=v(0,"D","double");Da.g=q(Da);Ea.g=q(Ea);Fa.g=q(Fa);Ga.g=q(Ga);Ha.g=q(Ha);Ia.g=q(Ia);Ja.g=q(Ja);Ka.g=q(Ka);function A(){}function y(){}y.prototype=A.prototype;A.prototype.b=function(){return this};A.prototype.f=function(){var a=ha(this).p.name,b=(+(this.o()>>>0)).toString(16);return a+"@"+b};A.prototype.o=function(){return za(this)};A.prototype.toString=function(){return this.f()};var Ba=w({a:0},"java.lang.Object",{a:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.$classData){var c=a.E||0;return!(c<b)&&(c>b||!a.C.isPrimitive)}return!1});A.prototype.$classData=Ba;
function z(){this.p=null}z.prototype=new y;z.prototype.constructor=z;z.prototype.f=function(){return(this.p.isInterface?"interface ":this.p.isPrimitive?"":"class ")+this.p.name};z.prototype.$classData=w({nb:0},"java.lang.Class",{nb:1,a:1});function B(){this.Ka=this.Va=null}B.prototype=new y;B.prototype.constructor=B;B.prototype.b=function(){La=this;this.Va=Ma(!1);this.Ka=Ma(!0);return this};B.prototype.$classData=w({zb:0},"java.lang.System$",{zb:1,a:1});var La=void 0;
function Na(){La||(La=(new B).b());return La}function Oa(){}Oa.prototype=new y;Oa.prototype.constructor=Oa;function Pa(){}Pa.prototype=Oa.prototype;function C(){this.Ha=null}C.prototype=new y;C.prototype.constructor=C;C.prototype.f=function(){return"DynamicVariable("+this.Ha+")"};C.prototype.J=function(a){this.Ha=a;return this};C.prototype.$classData=w({Gb:0},"scala.util.DynamicVariable",{Gb:1,a:1});function Qa(){}Qa.prototype=new y;Qa.prototype.constructor=Qa;function Ra(){}Ra.prototype=Qa.prototype;
function Sa(a,b){b=n(-862048943,b);b=n(461845907,b<<15|b>>>17|0);a^=b;return-430675100+n(5,a<<13|a>>>19|0)|0}function Ta(a){a=n(-2048144789,a^(a>>>16|0));a=n(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function Ua(a,b,c){var d=(new D).H(0);c=(new D).H(c);b.T(Va(function(k,h,m){return function(l){h.e=Sa(h.e,Wa(Xa(),l));m.e=1+m.e|0}}(a,c,d)));return Ta(c.e^d.e)}
function Ya(a,b,c,d,k){var h=Za();$a(b,c);a.T(Va(function(m,l,p,t){return function(G){if(l.e)ab(p,G),l.e=!1;else return $a(p,t),ab(p,G)}}(a,h,b,d)));$a(b,k);return b}function E(){this.t=!1;this.Na=this.U=this.D=null;this.$=!1;this.Ta=this.Pa=0}E.prototype=new y;E.prototype.constructor=E;
E.prototype.b=function(){bb=this;this.D=(this.t=!!(g.ArrayBuffer&&g.Int32Array&&g.Float32Array&&g.Float64Array))?new g.ArrayBuffer(8):null;this.U=this.t?new g.Int32Array(this.D,0,2):null;this.t&&new g.Float32Array(this.D,0,2);this.Na=this.t?new g.Float64Array(this.D,0,1):null;if(this.t)this.U[0]=16909060,a=1===((new g.Int8Array(this.D,0,8))[0]|0);else var a=!0;this.Pa=(this.$=a)?0:1;this.Ta=this.$?1:0;return this};
function xa(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.t)a.Na[0]=b,a=(new F).I(a.U[a.Ta]|0,a.U[a.Pa]|0);else{if(b!==b)a=!1,b=2047,c=+g.Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,c=0;else if(0===b)a=-Infinity===1/b,c=b=0;else{var d=(a=0>b)?-b:b;if(d>=+g.Math.pow(2,-1022)){b=+g.Math.pow(2,52);c=+g.Math.log(d)/.6931471805599453;c=+g.Math.floor(c)|0;c=1023>c?c:1023;var k=+g.Math.pow(2,c);k>d&&(c=-1+c|0,k/=2);k=d/k*b;d=+g.Math.floor(k);k-=d;d=.5>k?d:.5<k?1+d:0!==d%2?1+
d:d;2<=d/b&&(c=1+c|0,d=1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=b);b=c;c=d}else b=d/+g.Math.pow(2,-1074),c=+g.Math.floor(b),d=b-c,b=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c}c=+c;a=(new F).I(c|0,(a?-2147483648:0)|(b|0)<<20|c/4294967296|0)}return a.B^a.w}E.prototype.$classData=w({ec:0},"scala.scalajs.runtime.Bits$",{ec:1,a:1});var bb=void 0;function ya(){bb||(bb=(new E).b());return bb}function H(){}H.prototype=new y;H.prototype.constructor=H;H.prototype.b=function(){return this};
function va(a,b){a=0;for(var c=1,d=-1+(b.length|0)|0;0<=d;)a=a+n(65535&(b.charCodeAt(d)|0),c)|0,c=n(31,c),d=-1+d|0;return a}H.prototype.$classData=w({gc:0},"scala.scalajs.runtime.RuntimeString$",{gc:1,a:1});var cb=void 0;function wa(){cb||(cb=(new H).b());return cb}function I(){}I.prototype=new y;I.prototype.constructor=I;I.prototype.b=function(){return this};I.prototype.$classData=w({hc:0},"scala.scalajs.runtime.package$",{hc:1,a:1});var db=void 0;function eb(){db||(db=(new I).b())}
function J(){}J.prototype=new y;J.prototype.constructor=J;J.prototype.b=function(){return this};function Wa(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{var c=x();b=fb(c,a);c=c.X;x();a=(0>c?-(4294967296*+((0!==b?~c:-c|0)>>>0)+ +((-b|0)>>>0)):4294967296*c+ +(b>>>0))===a?b^c:xa(ya(),a)}return a}return sa(b)?(a=null===b?x().P:b,b=(new F).I(a.B,a.w),a=b.B,b=b.w,b===a>>31?a:a^b):ua(b)}
J.prototype.$classData=w({lc:0},"scala.runtime.Statics$",{lc:1,a:1});var gb=void 0;function Xa(){gb||(gb=(new J).b());return gb}function hb(){}hb.prototype=new y;hb.prototype.constructor=hb;function ib(){}ib.prototype=hb.prototype;function K(){this.j=null}K.prototype=new y;K.prototype.constructor=K;function jb(){}jb.prototype=K.prototype;
K.prototype.Ma=function(){if(void 0===g.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(eb(),a=b&&b.$classData&&b.$classData.k.z?b:(new kb).J(b),null!==a)if(lb(a))a=a.q;else throw eb(),lb(a)?a.q:a;else throw b;}this.stackdata=a}else g.Error.captureStackTrace(this),this.stackdata=this};K.prototype.Oa=function(){return this.j};K.prototype.f=function(){var a=ha(this).p.name,b=this.Oa();return null===b?a:a+": "+b};K.prototype.x=function(a){this.j=a;this.Ma()};function L(){this.Ea=0}
L.prototype=new Ra;L.prototype.constructor=L;L.prototype.b=function(){mb=this;this.Ea=va(wa(),"Seq");va(wa(),"Map");va(wa(),"Set");return this};function nb(a){var b=ob();if(a&&a.$classData&&a.$classData.k.Ya){var c=0;b=b.Ea;for(var d=a;!d.h();)a=d.r(),d=d.u(),b=Sa(b,Wa(Xa(),a)),c=1+c|0;c=Ta(b^c)}else c=Ua(b,a,b.Ea);return c}L.prototype.$classData=w({Hb:0},"scala.util.hashing.MurmurHash3$",{Hb:1,vc:1,a:1});var mb=void 0;function ob(){mb||(mb=(new L).b());return mb}function pb(){}pb.prototype=new y;
pb.prototype.constructor=pb;function qb(){}qb.prototype=pb.prototype;pb.prototype.f=function(){return"\x3cfunction0\x3e"};function rb(){}rb.prototype=new y;rb.prototype.constructor=rb;function sb(){}sb.prototype=rb.prototype;rb.prototype.f=function(){return"\x3cfunction1\x3e"};function M(){this.e=!1}M.prototype=new y;M.prototype.constructor=M;M.prototype.f=function(){return""+this.e};function Za(){var a=new M;a.e=!0;return a}M.prototype.$classData=w({ic:0},"scala.runtime.BooleanRef",{ic:1,a:1,c:1});
var ra=w({jc:0},"scala.runtime.BoxedUnit",{jc:1,a:1,c:1},void 0,void 0,function(a){return void 0===a});function D(){this.e=0}D.prototype=new y;D.prototype.constructor=D;D.prototype.f=function(){return""+this.e};D.prototype.H=function(a){this.e=a;return this};D.prototype.$classData=w({kc:0},"scala.runtime.IntRef",{kc:1,a:1,c:1});function N(){x();this.Aa=this.Lb=null}N.prototype=new y;N.prototype.constructor=N;
N.prototype.b=function(){tb=this;Na();var a=x(),b=+(new g.Date).getTime();fb(a,b);this.Aa=(new ub).b();a=new vb;if(null===this)throw eb(),lb(null)?null.q:null;wb(this.Aa,a);return this};N.prototype.$classData=w({ab:0},"example.Main$",{ab:1,a:1,qc:1,rc:1});var tb=void 0;function vb(){}vb.prototype=new qb;vb.prototype.constructor=vb;vb.prototype.$classData=w({bb:0},"example.Main$delayedInit$body",{bb:1,Lc:1,a:1,mc:1});
var qa=w({kb:0},"java.lang.Boolean",{kb:1,a:1,c:1,i:1},void 0,void 0,function(a){return"boolean"===typeof a});function O(){this.Ia=0}O.prototype=new y;O.prototype.constructor=O;O.prototype.f=function(){return g.String.fromCharCode(this.Ia)};function xb(a){var b=new O;b.Ia=a;return b}O.prototype.o=function(){return this.Ia};O.prototype.$classData=w({mb:0},"java.lang.Character",{mb:1,a:1,c:1,i:1});function yb(){this.j=null}yb.prototype=new jb;yb.prototype.constructor=yb;function zb(){}
zb.prototype=yb.prototype;function P(){this.Wa=null}P.prototype=new Pa;P.prototype.constructor=P;P.prototype.b=function(){Ab=this;this.Wa=(new C).J(Na().Va);(new C).J(Na().Ka);(new C).J(null);return this};P.prototype.$classData=w({Db:0},"scala.Console$",{Db:1,sc:1,a:1,tc:1});var Ab=void 0;function Q(){this.La=null}Q.prototype=new sb;Q.prototype.constructor=Q;Q.prototype.v=function(a){(0,this.La)(a)};function Va(a){var b=new Q;b.La=a;return b}
Q.prototype.$classData=w({dc:0},"scala.scalajs.runtime.AnonFunction1",{dc:1,Mc:1,a:1,O:1});function R(){this.X=0;this.P=null}R.prototype=new y;R.prototype.constructor=R;R.prototype.b=function(){Bb=this;this.P=(new F).I(0,0);return this};
function Cb(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+ba(1E9)|0)-(0!==b?ba(b):32+ba(a)|0)|0,d=c,k=0===(32&d)?1E9<<d:0;d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d;var h=a,m=b;for(a=b=0;0<=c&&0!==(-2097152&m);){var l=h,p=m,t=k,G=d;if(p===G?(-2147483648^l)>=(-2147483648^t):(-2147483648^p)>=(-2147483648^G))l=m,p=d,m=h-k|0,l=(-2147483648^m)>(-2147483648^h)?-1+(l-p|0)|0:l-p|0,h=m,m=l,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;l=d>>>1|0;k=k>>>1|0|d<<31;d=l}c=m;if(0===c?-1147483648<=(-2147483648^
h):-2147483648<=(-2147483648^c))c=4294967296*m+ +(h>>>0),h=c/1E9,k=h/4294967296|0,d=b,b=h=d+(h|0)|0,a=(-2147483648^h)<(-2147483648^d)?1+(a+k|0)|0:a+k|0,h=c%1E9|0;c=""+h;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}function fb(a,b){if(-9223372036854775808>b)return a.X=-2147483648,0;if(0x7fffffffffffffff<=b)return a.X=2147483647,-1;var c=b|0,d=b/4294967296|0;a.X=0>b&&0!==c?-1+d|0:d;return c}
R.prototype.$classData=w({fc:0},"scala.scalajs.runtime.RuntimeLong$",{fc:1,a:1,M:1,c:1});var Bb=void 0;function x(){Bb||(Bb=(new R).b());return Bb}function Db(){}Db.prototype=new y;Db.prototype.constructor=Db;function Eb(){}Eb.prototype=Db.prototype;
var ia=w({fb:0},"java.lang.String",{fb:1,a:1,c:1,Ra:1,i:1},void 0,void 0,function(a){return"string"===typeof a}),ka=w({lb:0},"java.lang.Byte",{lb:1,y:1,a:1,c:1,i:1},void 0,void 0,function(a){return ja(a)}),pa=w({ob:0},"java.lang.Double",{ob:1,y:1,a:1,c:1,i:1},void 0,void 0,function(a){return"number"===typeof a}),oa=w({pb:0},"java.lang.Float",{pb:1,y:1,a:1,c:1,i:1},void 0,void 0,function(a){return"number"===typeof a}),na=w({rb:0},"java.lang.Integer",{rb:1,y:1,a:1,c:1,i:1},void 0,void 0,function(a){return"number"===
typeof a&&(a|0)===a&&1/a!==1/-0}),ta=w({ub:0},"java.lang.Long",{ub:1,y:1,a:1,c:1,i:1},void 0,void 0,function(a){return sa(a)});function Fb(){this.j=null}Fb.prototype=new zb;Fb.prototype.constructor=Fb;function S(){}S.prototype=Fb.prototype;var ma=w({xb:0},"java.lang.Short",{xb:1,y:1,a:1,c:1,i:1},void 0,void 0,function(a){return la(a)});function T(){this.d=null}T.prototype=new y;T.prototype.constructor=T;e=T.prototype;e.b=function(){this.d="";return this};e.f=function(){return this.d};
e.H=function(a){T.prototype.b.call(this);if(0>a)throw(new U).b();return this};e.da=function(){return this.d.length|0};e.$classData=w({yb:0},"java.lang.StringBuilder",{yb:1,a:1,Ra:1,ib:1,c:1});function F(){this.w=this.B=0}F.prototype=new ib;F.prototype.constructor=F;e=F.prototype;e.f=function(){x();var a=this.B,b=this.w;return b===a>>31?""+a:0>b?"-"+Cb(-a|0,0!==a?~b:-b|0):Cb(a,b)};e.I=function(a,b){this.B=a;this.w=b;return this};e.H=function(a){F.prototype.I.call(this,a,a>>31);return this};
e.o=function(){return this.B^this.w};function sa(a){return!!(a&&a.$classData&&a.$classData.k.$a)}e.$classData=w({$a:0},"scala.scalajs.runtime.RuntimeLong",{$a:1,y:1,a:1,c:1,i:1});function Gb(){}Gb.prototype=new Eb;Gb.prototype.constructor=Gb;function Hb(){}Hb.prototype=Gb.prototype;function V(){this.j=null}V.prototype=new S;V.prototype.constructor=V;V.prototype.l=function(a){K.prototype.x.call(this,a);return this};
V.prototype.$classData=w({qb:0},"java.lang.IndexOutOfBoundsException",{qb:1,L:1,K:1,z:1,a:1,c:1});function Ib(){}Ib.prototype=new Eb;Ib.prototype.constructor=Ib;Ib.prototype.b=function(){return this};Ib.prototype.$classData=w({tb:0},"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{tb:1,eb:1,a:1,cb:1,jb:1,db:1});function U(){this.j=null}U.prototype=new S;U.prototype.constructor=U;U.prototype.b=function(){K.prototype.x.call(this,null);return this};
U.prototype.$classData=w({vb:0},"java.lang.NegativeArraySizeException",{vb:1,L:1,K:1,z:1,a:1,c:1});function Jb(){this.j=null}Jb.prototype=new S;Jb.prototype.constructor=Jb;Jb.prototype.b=function(){K.prototype.x.call(this,null);return this};Jb.prototype.$classData=w({wb:0},"java.lang.NullPointerException",{wb:1,L:1,K:1,z:1,a:1,c:1});function Kb(){this.j=null}Kb.prototype=new S;Kb.prototype.constructor=Kb;Kb.prototype.l=function(a){K.prototype.x.call(this,a);return this};
Kb.prototype.$classData=w({Ab:0},"java.lang.UnsupportedOperationException",{Ab:1,L:1,K:1,z:1,a:1,c:1});function Lb(){this.j=null}Lb.prototype=new S;Lb.prototype.constructor=Lb;Lb.prototype.l=function(a){K.prototype.x.call(this,a);return this};Lb.prototype.$classData=w({Bb:0},"java.util.NoSuchElementException",{Bb:1,L:1,K:1,z:1,a:1,c:1});function Mb(){}Mb.prototype=new Hb;Mb.prototype.constructor=Mb;function Nb(){}Nb.prototype=Mb.prototype;function Ob(){this.F=this.Qa=null}Ob.prototype=new Nb;
Ob.prototype.constructor=Ob;function Ma(a){var b=new Ob;b.Qa=a;(new Ib).b();b.F="";return b}Ob.prototype.$classData=w({sb:0},"java.lang.JSConsoleBasedPrintStream",{sb:1,oc:1,nc:1,eb:1,a:1,cb:1,jb:1,db:1,ib:1});function kb(){this.q=this.j=null}kb.prototype=new S;kb.prototype.constructor=kb;e=kb.prototype;e.ga=function(){return"JavaScriptException"};e.ea=function(){return 1};e.Ma=function(){this.stackdata=this.q};e.fa=function(a){switch(a){case 0:return this.q;default:throw(new V).l(""+a);}};
e.Oa=function(){var a=this.q;return void 0===a?"undefined":a.toString()};e.J=function(a){this.q=a;K.prototype.x.call(this,null);return this};e.o=function(){ob();var a=this.ea();if(0===a)a=this.ga(),a=va(wa(),a);else{for(var b=-889275714,c=0;c<a;)b=Sa(b,Wa(Xa(),this.fa(c))),c=1+c|0;a=Ta(b^a)}return a};function lb(a){return!!(a&&a.$classData&&a.$classData.k.Za)}e.$classData=w({Za:0},"scala.scalajs.js.JavaScriptException",{Za:1,L:1,K:1,z:1,a:1,c:1,Xa:1,W:1,M:1});function W(){}W.prototype=new y;
W.prototype.constructor=W;function Pb(){}Pb.prototype=W.prototype;W.prototype.Ua=function(a,b,c){return this.Y((new X).b(),a,b,c).n.d};W.prototype.Y=function(a,b,c,d){return Ya(this,a,b,c,d)};
W.prototype.Fa=function(){a:{var a=ha(this).p.name;for(var b=-1+(a.length|0)|0;;)if(-1!==b&&36===(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;if(-1===b||46===(65535&(a.charCodeAt(b)|0)))a="";else for(var c="";;){for(var d=1+b|0;;)if(-1!==b&&57>=(65535&(a.charCodeAt(b)|0))&&48<=(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;for(var k=b;;)if(-1!==b&&36!==(65535&(a.charCodeAt(b)|0))&&46!==(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;var h=1+b|0;if(b===k&&d!==(a.length|0)){a=c;break a}for(;;)if(-1!==
b&&36===(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;k=-1===b?!0:46===(65535&(a.charCodeAt(b)|0));var m;(m=k)||(m=65535&(a.charCodeAt(h)|0),m=!(90<m&&127>m||65>m));if(m){d=a.substring(h,d);h=c;if(null===h)throw(new Jb).b();c=""===h?d:""+d+xb(46)+c;if(k){a=c;break a}}}}return a};function Qb(a,b){for(var c=b;!a.h()&&0<c;)a=a.u(),c=-1+c|0;if(0>b||a.h())throw(new V).l(""+b);return a.r()}function Rb(){}Rb.prototype=new Pb;Rb.prototype.constructor=Rb;function Sb(){}Sb.prototype=Rb.prototype;
function Tb(){}Tb.prototype=new Sb;Tb.prototype.constructor=Tb;function Ub(){}Ub.prototype=Tb.prototype;Tb.prototype.f=function(){return this.Ua(this.Fa()+"(",", ",")")};Tb.prototype.o=function(){return nb(this)};function Vb(){}Vb.prototype=new Ub;Vb.prototype.constructor=Vb;function Wb(){}Wb.prototype=Vb.prototype;function Y(){}Y.prototype=new Ub;Y.prototype.constructor=Y;function Xb(){}Xb.prototype=Y.prototype;Y.prototype.v=function(a){Qb(this,a|0)};
Y.prototype.T=function(a){for(var b=this;!b.h();)a.v(b.r()),b=b.u()};Y.prototype.o=function(){return nb(this)};Y.prototype.Fa=function(){return"List"};function Yb(){this.N=this.ca=null}Yb.prototype=new Xb;Yb.prototype.constructor=Yb;e=Yb.prototype;e.r=function(){return this.ca};e.ga=function(){return"::"};e.ea=function(){return 2};e.u=function(){return this.N};e.h=function(){return!1};e.fa=function(a){switch(a){case 0:return this.ca;case 1:return this.N;default:throw(new V).l(""+a);}};
function Zb(a){var b=new Yb,c=$b();b.ca=a;b.N=c;return b}e.$classData=w({Ob:0},"scala.collection.immutable.$colon$colon",{Ob:1,Ya:1,ja:1,ia:1,ka:1,a:1,xa:1,ya:1,Da:1,Ba:1,za:1,ra:1,qa:1,ua:1,pa:1,Ca:1,sa:1,la:1,ma:1,ta:1,W:1,va:1,ha:1,O:1,na:1,oa:1,wa:1,Qb:1,Sb:1,Pb:1,Tb:1,Eb:1,Ib:1,Jb:1,Xa:1,Kb:1,M:1,c:1});function ac(){}ac.prototype=new Xb;ac.prototype.constructor=ac;e=ac.prototype;e.b=function(){return this};e.r=function(){throw(new Lb).l("head of empty list");};e.ga=function(){return"Nil"};
e.ea=function(){return 0};e.u=function(){throw(new Kb).l("tail of empty list");};e.h=function(){return!0};e.fa=function(a){throw(new V).l(""+a);};e.$classData=w({Rb:0},"scala.collection.immutable.Nil$",{Rb:1,Ya:1,ja:1,ia:1,ka:1,a:1,xa:1,ya:1,Da:1,Ba:1,za:1,ra:1,qa:1,ua:1,pa:1,Ca:1,sa:1,la:1,ma:1,ta:1,W:1,va:1,ha:1,O:1,na:1,oa:1,wa:1,Qb:1,Sb:1,Pb:1,Tb:1,Eb:1,Ib:1,Jb:1,Xa:1,Kb:1,M:1,c:1});var bc=void 0;function $b(){bc||(bc=(new ac).b());return bc}function cc(){}cc.prototype=new Wb;
cc.prototype.constructor=cc;function dc(){}dc.prototype=cc.prototype;function ub(){this.s=this.m=null;this.ba=!1;this.A=0}ub.prototype=new dc;ub.prototype.constructor=ub;e=ub.prototype;e.b=function(){this.m=$b();this.ba=!1;this.A=0;return this};e.Z=function(a){if(0>a||a>=this.A)throw(new V).l(""+a);return Qb(this.m,a)};e.v=function(a){this.Z(a|0)};e.h=function(){return 0===this.A};e.Ua=function(a,b,c){return this.m.Y((new X).b(),a,b,c).n.d};e.T=function(a){for(var b=this.m;!b.h();)a.v(b.r()),b=b.u()};
e.Y=function(a,b,c,d){return Ya(this.m,a,b,c,d)};function wb(a,b){if(a.ba&&!a.h()){var c=a.m,d=a.s.N;a.m=$b();a.s=null;a.ba=!1;for(a.A=0;c!==d;)wb(a,c.r()),c=c.u()}a.h()?(a.s=Zb(b),a.m=a.s):(c=a.s,a.s=Zb(b),c.N=a.s);a.A=1+a.A|0}e.Fa=function(){return"ListBuffer"};
e.$classData=w({Yb:0},"scala.collection.mutable.ListBuffer",{Yb:1,Gc:1,Ub:1,ja:1,ia:1,ka:1,a:1,xa:1,ya:1,Da:1,Ba:1,za:1,ra:1,qa:1,ua:1,pa:1,Ca:1,sa:1,la:1,ma:1,ta:1,W:1,va:1,ha:1,O:1,na:1,oa:1,wa:1,$b:1,Xb:1,cc:1,Fb:1,ac:1,Wb:1,Cb:1,Sa:1,Hc:1,Ic:1,Nb:1,Mb:1,Cc:1,zc:1,Dc:1,Zb:1,Vb:1,Bc:1,Ac:1,Ec:1,M:1,c:1});function X(){this.n=null}X.prototype=new Wb;X.prototype.constructor=X;e=X.prototype;e.b=function(){X.prototype.gb.call(this);return this};e.Z=function(a){a=65535&(this.n.d.charCodeAt(a)|0);return xb(a)};
e.v=function(a){a=65535&(this.n.d.charCodeAt(a|0)|0);xb(a)};e.f=function(){return this.n.d};e.T=function(a){for(var b=0,c=this.da();b<c;)a.v(this.Z(b)),b=1+b|0};function $a(a,b){a=a.n;a.d=""+a.d+b}e.gb=function(){var a=(new T).H(16);a.d=""+a.d;X.prototype.hb.call(this,a)};e.da=function(){return this.n.da()};e.hb=function(a){this.n=a};function ab(a,b){var c=a.n;c.d+=""+b;return a}e.o=function(){return nb(this)};
e.$classData=w({bc:0},"scala.collection.mutable.StringBuilder",{bc:1,Ub:1,ja:1,ia:1,ka:1,a:1,xa:1,ya:1,Da:1,Ba:1,za:1,ra:1,qa:1,ua:1,pa:1,Ca:1,sa:1,la:1,ma:1,ta:1,W:1,va:1,ha:1,O:1,na:1,oa:1,wa:1,$b:1,Xb:1,cc:1,Fb:1,ac:1,Wb:1,Cb:1,Sa:1,Ra:1,Jc:1,wc:1,xc:1,Kc:1,Fc:1,yc:1,uc:1,i:1,Zb:1,Vb:1,Nb:1,Mb:1,M:1,c:1});var ec;tb||(tb=(new N).b());ec=tb;var fc;fc=new (Ca(ia).aa)([]);ec.Lb=fc;
for(var gc=ec.Aa.m;!gc.h();){gc.r();Ab||(Ab=(new P).b());for(var hc=Ab.Wa.Ha,Z="Hi\n";""!==Z;){var ic=Z.indexOf("\n")|0;if(0>ic)hc.F=""+hc.F+Z,Z="";else{var jc=""+hc.F+Z.substring(0,ic);g.console&&(hc.Qa&&g.console.error?g.console.error(jc):g.console.log(jc));hc.F="";Z=Z.substring(1+ic|0)}}gc=gc.u()};
}).call(this);
//# sourceMappingURL=tglogin4s-opt.js.map
